baseURL = "https://honux77.github.io/"
languageCode = "ko-kr"
title = "Honux Blog"
theme = "hugo.386k"
publishdir = "./docs/"

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
    # The name to display as main title in the home page
    mainpagetitle = "HONUX.386"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "응답하라 호눅스 90!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "테마가 맘에 들어서 설치해 본 깃헙 블로그"

    # The name to display in the copyright section in the footer
    copyrightname = "Honux2020"

   copyrighturl = "https://codesquad.kr"

   showhugo = true

    # Urls for social networks
    github = "https://github.com/honux77"
    
